"""Initial-temp

Revision ID: 038fa45834d3
Revises: 
Create Date: 2025-11-06 03:08:25.823734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038fa45834d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recompensa',
    sa.Column('id_recompensa', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('puntos_requeridos', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
        # Almacenar JSON como texto para compatibilidad amplia con MySQL/MariaDB
        sa.Column('requisitos', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_recompensa')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tecnica',
    sa.Column('id_tecnica', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_estimada', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_tecnica')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
        # Usar DateTime sin bandera timezone para evitar incompatibilidades
        sa.Column('fecha_registro', sa.DateTime(), nullable=False),
        sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('progreso',
    sa.Column('id_progreso', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tareas_completadas', sa.Integer(), nullable=False),
    sa.Column('sesiones_completadas', sa.Integer(), nullable=False),
    sa.Column('puntos_acumulados', sa.Integer(), nullable=False),
    sa.Column('minutos_estudio', sa.Integer(), nullable=False),
    sa.Column('sesiones_realizadas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_progreso')
    )
    op.create_table('recompensausuario',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('id_recompensa', sa.String(length=36), nullable=False),
        sa.Column('fecha_obtenida', sa.DateTime(), nullable=False),
    sa.Column('consumida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_recompensa'], ['recompensa.id_recompensa'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_recompensa')
    )
    op.create_table('sala',
    sa.Column('id_sala', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('creador_id', sa.String(length=36), nullable=False),
    sa.Column('max_participantes', sa.Integer(), nullable=True),
    sa.Column('es_privada', sa.Boolean(), nullable=True),
    sa.Column('codigo_acceso', sa.String(length=6), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sala')
    )
    op.create_table('sesion',
    sa.Column('id_sesion', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('tecnica_id', sa.String(length=36), nullable=False),
        sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
        sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_real', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('es_grupal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnica.id_tecnica'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_table('salasesion',
    sa.Column('id_sala', sa.String(length=36), nullable=False),
    sa.Column('id_sesion', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id_sala'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion.id_sesion'], ),
    sa.PrimaryKeyConstraint('id_sala', 'id_sesion')
    )
    op.create_table('sesiontecnicaparam',
    sa.Column('id_param', sa.String(length=36), nullable=False),
    sa.Column('id_sesion', sa.String(length=36), nullable=False),
    sa.Column('parametro', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesion.id_sesion'], ),
    sa.PrimaryKeyConstraint('id_param')
    )
    op.create_table('tarea',
    sa.Column('id_tarea', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('sala_id', sa.String(length=36), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=6), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.id_sala'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_tarea')
    )
    op.create_table('usuariosala',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('id_sala', sa.String(length=36), nullable=False),
        sa.Column('fecha_union', sa.DateTime(), nullable=False),
    sa.Column('rol_en_sala', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id_sala'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_sala')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuariosala')
    op.drop_table('tarea')
    op.drop_table('sesiontecnicaparam')
    op.drop_table('salasesion')
    op.drop_table('sesion')
    op.drop_table('sala')
    op.drop_table('recompensausuario')
    op.drop_table('progreso')
    op.drop_table('usuario')
    op.drop_table('tecnica')
    op.drop_table('rol')
    op.drop_table('recompensa')
    # ### end Alembic commands ###
